package com.psr.dynamodblearning.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@DynamoDBTable(tableName = "employee")
@AllArgsConstructor
@NoArgsConstructor
@Data
@ToString
public class Employee {

    @DynamoDBHashKey(attributeName = "employeeId")
    @DynamoDBAutoGeneratedKey
    private String employeeId;

    @DynamoDBAttribute
    private String employeeName;

    @DynamoDBAttribute
    private String employeeEmail;

    @DynamoDBAttribute
    private String employeeMobile;
}
